export const MAIN_URL = "https://api.moviesexplore.nomoredomainsrocks.ru";
export const MOVIES_URL = "https://api.nomoreparties.co"
export const EMAIL_REGEX = /^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/
export const HTTP_STATUS_CONFLICT = 409;
export const HTTP_STATUS_UNAUTHORIZED = 401;
export const HTTP_STATUS_INTERNAL = 500;
export const INTERNAL_SERVER_ERROR = "На сервере произошла ошибка";
export const MEDIUM_SCREEN_SIZE = 1140;
export const SMALL_SCREEN_SIZE = 708;
export const INITIAL_SCREEN_SIZE = 12;
export const INITIAL_ON_MEDIUM_SCREEN = 8;
export const INITIAL_ON_SMALL_SCREEN = 5;
export const ADD_ON_LARGE_SCREEN = 3;
export const ADD_ON_MEDIUM_SCREEN = 2;