export const MAIN_URL = "https://api.moviesexplore.nomoredomainsrocks.ru";
export const MOVIES_URL = "https://api.nomoreparties.co"
export const EMAIL_REGEX = /^[\w-]+(\.[\w-]+)*@([\w-]+\.)+[a-zA-Z]{2,7}$/
export const HTTP_STATUS_CONFLICT = 409;
export const HTTP_STATUS_UNAUTHORIZED = 401;
export const HTTP_STATUS_INTERNAL = 500;
export const INTERNAL_SERVER_ERROR = "На сервере произошла ошибка";
export const mediumScreenSize = 1140;
export const smallScreenSize = 708;
export const initialOnLargeScreen = 12;
export const initialOnMediumScreen = 8;
export const initialOnSmallScreen = 5;
export const addOnLargeScreen = 3;
export const addOnMediumScreen = 2;